name: SimpleHub
version: '${project.version}'
main: xyz.glowberry.simplehub.SimpleHub
api-version: '1.21'
commands:
  hub:
    description: teleports player to hub
    usage: /hub
    aliases: [h, lobby]
